services:
  mongodb:
    image: 'mongodb/mongodb-atlas-local:latest'
    environment:
      - 'MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}'
      - 'MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}'
    volumes:
      - 'sail-mongodb:/data/db'
    ports:
      - '${FORWARD_MONGODB_PORT:-27017}:27017'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mongosh
        - 'mongodb://localhost:27017/admin'
        - '--eval=db.runCommand({ping:1})'
      retries: 3
      timeout: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./:/var/www:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    user: "1000:1000"
    networks:
      - sail

  nginx:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mongodb:
    driver: local
